"""empty message

Revision ID: a8339c4c3408
Revises: c72cd39d08a4
Create Date: 2020-09-16 14:57:26.008989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8339c4c3408'
down_revision = 'c72cd39d08a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('won', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'won')
    # ### end Alembic commands ###
